import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/providers/QueryProvider";
import HeaderTemplate from "@/components/templates/header/Header.template";
import { ReduxProvider } from "@/providers/ReduxProvider";
import { ThemeApplier } from "@/providers/ThemeApplier";

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cinzel.variable}>
        <ReduxProvider>
          <ThemeApplier />
          <HeaderTemplate title="Top Luxury Buildings in South Florida" />
          <QueryProvider>{children}</QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
